export { default as Header } from './layout/Header'
export { default as Footer } from './layout/Footer'
export { default as Hero } from './sections/Hero'
export { default as About } from './sections/About'
export { default as Projects } from './sections/Projects'
export { default as Contact } from './sections/Contact'
